#!/bin/bash
DIR=$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)
show_help() {
cat << EOF
USAGE: ${0##*/} [-h] [-g GENETREES] [-t CONSENSUS THRESHOLD] [-n NUMBER OF SAMPLES] [-o OUTPATH] [ -s TRUE SPECIES TREE]
Generates a pool of branches with their posterior probabilities using Astral.

	-h	HELP		display help and exit
	-g  	GENETREES 	The gene trees filename
	-t	THRESHOLD 	The consensus threshold to generate randomly resolved samples.
	-n 	SAMPLE NUMS 	The number of replicates, generated by randomly resolving consensus tree of given genetrees.
	-o 	OUTPUT FOLDER	The output folder to put the results there.
	-s 	SPECIES TREE 	The true species tree to compare the results.
EOF
}

if [ $# -lt 1 ]; then 
	show_help
	exit 1 
fi

t=0.2;
n=10;

while getopts "hg:t:n:o:s:" opt; do
        case $opt in
        h)
                show_help
                exit 0;
                ;;
        g)
                gt=$OPTARG
                ;;
        t)
                t=$OPTARG
                ;;
        n)
                n=$OPTARG
                ;;
        o)
                out=$OPTARG
                ;;
	s)
		s=$OPTARG
		;;
	?)
		show_help
		exit 1;
		;;
	esac
done
rm $out/*
python $DIR/randomResolvedSampleGenerator.py -g $gt -o $out -t $t -n $n
for x in `cat $out/random_resolved_trees.nwk`; do
	y=$(echo $x | sed -e 's/\[&U\]//g')
	tmp=`mktemp`
	echo $y>$tmp
	echo $y>>$out/tmp
	java -jar $WS_HOME/ASTRAL/astral.4.9.1.jar -i $gt -q $tmp -t 2 >> $out/randomly_resolved_tree.nwk 2>>$out/randomly_resolved_trees.stat.txt;
	rm $tmp
done
java -jar $WS_HOME/ASTRAL/astral.4.9.1.jar -i $s -q $s -t 2 >> $out/sp.nwk 2>>$out/sp.stat.txt;
$DIR/uniquePoolOfBranches.py -i $out/randomly_resolved_trees.stat.txt -o $out;
$DIR/checkBranchIfAvail.py -i $out/poolOfBranches.txt -o $out -s $out/sp.stat.txt;
cat $out/tmp 	> $out/random_resolved_trees.nwk
rm $out/tmp
